/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker/wrangler-env.d.ts` (hash: 7dfa1bcf34eb414d6c7f295771e0dae3)
interface __BaseEnv_Env {
  GUILD_DB: D1Database;
  GITHUB_CLIENT_SECRET: string;
  AUTH_COOKIE_SECRET: string;
  GUILD_ISSUER_KEY_ID: string;
  GUILD_ISSUER_PRIVATE_JWK: string;
  MISSIONS: DurableObjectNamespace<import("./index").MissionCoordinator>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
    durableNamespaces: "MissionCoordinator";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "GITHUB_CLIENT_SECRET"
      | "AUTH_COOKIE_SECRET"
      | "GUILD_ISSUER_KEY_ID"
      | "GUILD_ISSUER_PRIVATE_JWK"
    >
  > {}
}
